version: "3.7"

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 7654:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: /run/secrets/db_user_password
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html
    secrets:
      - db_user_password

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: /run/secrets/db_user_password
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
    volumes:
      - db:/var/lib/mysql
    secrets:
      - db_root_password
      - db_user_password

volumes:
  wordpress:
  db:

secrets:
  db_root_password:
    file: db_root_password.txt
  db_user_password:
    file: db_user_password.txt